# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: /v1/
                check_path: /v1/user/security/login_check
                username_parameter: username
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
            logout:       true
            anonymous:    true

        api:
            pattern:   ^/v1
            stateless: true
            lexik_jwt: ~

    access_control:
        - { path: ^/v1/user/security/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/items, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/users/me, role: ROLE_USER }
