uaw_rest:
    resource: "@UAWRestBundle/Resources/config/routing/default.yml"
    prefix:   /
    requirements:
        _method: GET 

user_api_security_check:
    pattern: /user/security/login_check
    defaults: { _controller: UAWRestBundle:Security:check }
    requirements:
        _method: POST

rest_user:
    type:     rest
    resource: UAW\Bundle\RestBundle\Controller\UserController

rest_items:
    type:     rest
    resource: UAW\Bundle\RestBundle\Controller\ItemController
